dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
sudo: false
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock
script: ./gradlew check -is
