mod_id=tropicraft
mod_version=9.10.1
project_id=254794
release_type=beta
minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2)
loader_version_range=[4,)
neo_version=26.1.2.17-beta
neo_version_range=[26.1.2.17-beta,)
registrate_version=1.5.1

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
