mod_id=tropicraft
mod_version=9.9.0
project_id=254794
release_type=beta
minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.21.9)
loader_version_range=[4,)
neo_version=21.8.2-beta
neo_version_range=[21.8.0-beta,)
parchment_version=2025.07.18
registrate_version=1.3.0+nknown

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
