mod_id=tropicraft
mod_version=9.11.2
project_id=254794
release_type=beta
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
loader_version_range=[4,)
neo_version=26.2.0.57
neo_version_range=[26.2.0.57,)
registrate_version=MC26.2-1.6.0
registrate_version_range=[MC26.2,MC26.3)

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
