name: Bug Report
description: Report a bug or crash
labels: [bug, new]
assignees: [NotActuallyTerry]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much information as you can so that we are able to reproduce and best address the issue.
  - type: input
    id: mod-version
    attributes:
      label: Tropicraft version
      description: |
        You can find the version of the mod in the mods file name or in-game in the 'Mods' button on the main menu.
      placeholder: 9.7.0
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: 1.21.0
    validations:
      required: true
  - type: input
    id: loader-version
    attributes:
      label: (Forge / Neo Forge) Version
      description: |
        You can get this from the main menu screen in the bottom left corner of the screen.
      placeholder: 21.0.98
    validations:
      required: false
  - type: input
    id: bugdesc
    attributes:
      label: Describe the issue
      description: |
        A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how we can reproduce the issue
      placeholder: |
        1. Place a Sapling block in the Tropics on a Tuesday...
        2. Use Bonemeal on the sapling...
        3. See error...
    validations:
      required: true
  - type: input
    id: expectedBehaviour
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: "Link(s) to any log files that you can provide, typically, /logs/debug.log and /logs/latest.log"
      placeholder: |
        https://pastebin.com/
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
