---
name: Lint Code Base

on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Checkstyle - Google Java Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: 1.16
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
