name: Build & Release Tropicraft

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      env:
        GHA_RELEASE_WORKFLOW: True
      with:
        arguments: build

    - name: Set up Environment Variables
      id: env-vars
      run: echo "##[set-output name=mcversion;]$(grep 'minecraft_version' gradle.properties | cut -f2- -d=)"

    - name: Publish to Services (Release)
      uses: Kir-Antipov/mc-publish@v3.1
      if: "!github.event.release.prerelease"
      with:
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-type: release
        game-versions: |
          ${{ steps.env-vars.outputs.mcversion }}

    - name: Publish to Services (Beta)
      uses: Kir-Antipov/mc-publish@v3.1
      if: "github.event.release.prerelease"
      with:
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-type: beta
        game-versions: |
          ${{ steps.env-vars.outputs.mcversion }}
