name: Build & Release Tropicraft

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build Jarfile
      run: ./gradlew build
      env:
        GHA_RELEASE_WORKFLOW: True

    - name: Set up Environment Variables
      id: env-vars
      run: echo "##[set-output name=mcversion;]$(grep 'minecraft_version' gradle.properties | cut -f2- -d=)"

    - name: Publish to Services (Release)
      uses: Kir-Antipov/mc-publish@v3
      if: "!github.event.release.prerelease"
      with:
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        modrinth-id: 20zpzIT1
        curseforge-id: 254794
        version-type: release
        files: build/libs/!(*-dev|*-slim|*-sources|*-javadoc).jar
        game-versions: |
          ${{ steps.env-vars.outputs.mcversion }}
        loaders: |
          neoforge
        java: |
          21

    - name: Publish to Services (Beta)
      uses: Kir-Antipov/mc-publish@v3
      if: "github.event.release.prerelease"
      with:
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        modrinth-id: 20zpzIT1
        curseforge-id: 254794
        version-type: beta
        files: build/libs/!(*-dev|*-slim|*-sources|*-javadoc).jar
        game-versions: |
          ${{ steps.env-vars.outputs.mcversion }}
        loaders: |
          neoforge
        java: |
          21
